<?php
/*
 * Plugin Name: TFS Jive
 * Version: 1.2
 * Plugin URI: http://dougal.gunters.org/blog/2004/08/30/text-filter-suite
 * Description: Jive filter, sucka! (Requires TFS Core)
 * Author: Dougal Campbell
 * Author URI: http://dougal.gunters.org/
 */

// Borrowed fudd, jive, kraut, and chef from Kalsey's MovableJive filter
//   http://kalsey.com/blog/2003/02/movablejive/

// These filters (particularly 'kraut' and 'jive' might contain something
// that could offend you or your readers. Edit and/or use at your own risk.

function jive($content) {
	return filter_cdata_content($content,'jive_filter');
}

function jive_filter($content) {
	$content = $content[1];

	$patterns = array(
	'%file%' => 'stash',
	'%send%' => "t'row",
	'%program%' => 'honky code',
	'%atlas%' => 'Isaac',
	'%unix%' => 'slow mo-fo',
	'%UNIX%' => 'that slow mo-fo',
	'%takes%' => "snatch'd",
	'%Mexican%' => 'wet-back',
	'%Italian%' => 'greaser',
	'%take%' => 'snatch',
	"%don't%" => "duzn't",
	'%jive%' => 'JIBE',
	'%fool%' => 'honkyfool',
	'%modem%' => 'doodad',
	'%e the %' => 'e da damn ',
	'%a the %' => 'a da damn ',
	'%t the %' => 't da damn ',
	'%d the %' => 'd da damn ',
	'% man %' => ' dude ',
	'%woman%' => 'mama',
	'%girl%' => 'goat',
	'%somethin%' => "sump'n",
	'% lie %' => ' honky jibe ',
	'%([a-b]\.)%' => '$1 Sheeeiit.',
	'%([e-f]\.)%' => '$1 What it is, Mama!',
	'%([i-j]\.)%' => "$1 Ya' know?",
	'%([m-n]\.)%' => "$1 'S coo', bro.",
	'%([q-r]\.)%' => '$1 Ah be baaad...',
	'%([u-v]\.)%' => '$1 Man!',
	'%([y-z]\.)%' => '$1 Slap mah fro!',
	'%Sure%' => "Sho' nuff",
	'%sure%' => "sho' nuff",
	'% get	%' => ' git',
	'%will have%' => "gots'ta",
	'%will%' => "gots'ta ",
	'%got to%' => "gots'ta",
	'%I am%' => "I's gots'ta be",
	'%am not %' => 'aint ',
	'%is not %' => 'aint ',
	'%are not %' => 'aint',
	'% are your	%' => " is yo' ",
	'% are you	%' => ' you is ',
	'% hat %' => ' fedora ',
	'% shoe %' => ' kicker ',
	"%haven't%" => 'aint',
	'%have to%' => "gots'ta",
	'%have%' => "gots'",
	'% has%' => " gots'ta",
	'%come over%' => 'mosey on down',
	'% come %' => ' mosey on down ',
	'%!%' => '.  Right On!',
	'%buy	%' => 'steal',
	'% car %' => ' wheels ',
	'%drive%' => 'roll',
	'% eat %' => ' feed da bud ',
	'% black %' => ' brother ',
	'% negro %' => ' brother',
	'%white%' => 'honky',
	'%nigger%' => ' gentleman ',
	'%nice%' => "supa' fine",
	'%person%' => "sucka'",
	'% thing%' => ' wahtahmellun',
	'%home%' => 'plantation',
	'%name%' => 'dojigger',
	'% path%' => ' alley',
	'%computer%' => 'clunker',
	'%or%' => "o'",
	'%killed%' => 'wasted',
	'%president%' => 'super-dude',
	'%prime minister%' => 'super honcho',
	'%injured%' => 'hosed',
	'%government%' => "guv'ment",
	'%knew%' => 'knowed',
	'%because%' => "a'cuz",
	'%Because%' => "A'cuz",
	'%your%' => "yo'",
	'%Your%' => "Yo'",
	'%four%' => 'foe',
	'%got%' => 'gots',
	'%super%' => 'hella',
	'%very%' => 'hella',
	"%aren't%" => "ain't",
	'%young%' => 'yung',
	'%you%' => "ya'",
	'%You%' => "You's",
	'%first%' => 'fust',
	'%police%' => 'honky pigs',
	'% string%' => " chittlin'",
	'% read%' => ' eyeball',
	'%write%' => 'scribble',
	'%th%' => 'd',
	'%Th%' => 'D',
	'%ing%' => "in'",
	'% a %' => ' some ',
	'% to\s+%' => " t'",
	'%tion%' => 'shun',
	'% almost %' => " mos' ",
	'% from%' => ' fum',
	'% because %' => " cuz' ",
	"%you're%" => 'youse',
	"%You're%" => 'Youse',
	'%alright%' => "coo'",
	'%okay%' => "coo'",
	'%er %' => "a' ",
	'%known%' => 'knode',
	'%want%' => "wants'",
	'%beat%' => "whup'",
	'%exp%' => "'sp",
	'%exs%' => "'s",
	'% exc%' => " 's",
	'% ex%' => " 'es",
	'%like%' => 'likes',
	'%did	%' => 'dun did',
	'%kind of%' => "kind'a",
	'%women%' => 'honky chicks',
	'% men %' => ' dudes ',
	'% mens %' => ' dudes ',
	'% man %' => ' dude ',
	'%woman%' => 'honky chick',
	'%dead%' => 'wasted',
	'%good%' => 'baaaad',
	'%open %' => 'jimmey ',
	'%opened %' => "jimmey'd ",
	'% very%' => ' real',
	'%per%' => "puh'",
	'%pera%' => "puh'",
	'%oar%' => "o'",
	'% can%' => ' kin',
	'%just %' => 'plum ',
	'%detroit%' => 'Mo-town',
	'%western electric%' => "da' cave",
	'% believe%' => " recon'",
	'%[Ii]ndianapolis%' => 'Nap-town',
	'% [Jj]ack%' => ' Buckwheat',
	'% [Bb]ob %' => " Liva' Lips ",
	'% [Pp]hil %' => ' dat fine soul ',
	'% [Mm]ark %' => ' Amos ',
	'%[Rr]ober%' => 'Leroy',
	'%[Ss]andy%' => 'dat fine femahnaine ladee',
	'%[Jj]ohn %' => "Raz'tus ",
	'% [Pp]aul%' => " Fuh'rina",
	'%[Rr]eagan%' => 'Kingfish',
	'%[Dd]avid%' => 'Issac',
	'%[Rr]onald%' => 'Rolo',
	'% [Jj]im %' => ' Bo-Jangles ',
	'% [Mm]ary%' => ' Snow Flake',
	'%[Ll]arry%' => 'Remus',
	'%[Jj]oe%' => "Massa' ",
	'%[Jj]oseph%' => "Massa' ",
	'%mohammed%' => "liva' lips",
	'%pontiff%' => "wiz'",
	'%pope%' => "wiz'",
	'%pravda%' => 'dat commie rag',
	'%broken%' => "bugger'd",
	'%strange %' => 'funky ',
	'%dance %' => 'boogy ',
	'% house%' => ' crib',
	'%ask	%' => "ax'",
	'% so %' => " so's ",
	'%head%' => "'haid",
	'%boss%' => 'main man',
	'%wife%' => 'mama',
	'%people%' => "sucka's",
	'%money%' => "bre'd",
	'%([a-z]):%' => '$1, dig dis:',
	'%amateur%' => "begina'",
	'%radio	%' => "transista'",
	'% of %' => ' uh ',
	'%what%' => 'whut',
	'%does%' => 'duz',
	'%was%' => 'wuz',
	'% were%' => ' wuz',
	'%understand it%' => 'dig it',
	'%understand%' => 'dig it',
	'% my%' => " mah'",
	'% [Ii] %' => " ah' ",
	'%meta%' => "meta-fuckin'",
	'%hair%' => 'fro',
	'%talk%' => 'rap',
	'%music%' => 'beat',
	'%basket%' => 'hoop',
	'%football%' => 'ball',
	'%friend%' => 'homey',
	'%school%' => 'farm',
	'%boss%' => 'Man',
	'%want to%' => 'wanna',
	'%wants to%' => "be hankerin' aftah",
	'%well%' => 'sheeit',
	'%Well%' => 'Sheeit',
	'%big%' => 'big-ass',
	'%bad%' => 'bad-ass',
	'%small%' => 'little-ass',
	'%sort of%' => 'radical',
	'% is %' => ' be ',
	'%water%' => 'booze',
	'%book%' => "scribblin'",
	'%magazine%' => 'issue of GQ',
	'%paper%' => 'sheet',
	'%\bup\b%' => 'down',
	'%\bdown\b%' => 'waaay down',
	'%break%' => 'boogie',
	'%Hi%' => "'Sup, dude",
	'%VAX%' => 'pink Cadillac',
	);

	$content = array_apply_regexp($patterns,$content);

	return $content;
}

?>